---
# For v4.x, nice_nano_v2 is now: nice_nano//zmk or nice_nano@2.0.0//zmk
# The "//zmk" suffix is required for ZMK variants
board: [ "nice_nano//zmk" ]
shield: [ "chonkeeb_left", "chonkeeb_right", "settings_reset" ]
